### ISSUE TITLE
Fougerite Console going crazy sometimes

### ISSUE THREAD

**Issue by SnakeTheRipper** [Notulp/Fougerite#21] opened 2014-12-28 18:53 UTC
I don't know how to replicate this, just happens.

http://dretaxmc.eu/snakescreen/dafuqrust.swf

**Comment by mikecrews** [comment] 2015-01-01 22:15
dupe of https://github.com/Notulp/Fougerite/issues/15

**Closed by mikecrews** 2015-01-01 22:15 UTC
Labels: duplicate

**Comment by SnakeTheRipper** [comment] 2015-01-01 22:53
I meant the fact that when you write a new line appears on top of that line, with the previous message, not the NavMesh error spam.

**Comment by mikecrews** [comment] 2015-01-02 00:10
Also, Shockwave Flash - are you fucking kidding me?

**Comment by balu92** [comment] 2015-01-02 10:00
I think it's a bug with rust's server console, maybe unity!?
And yeah, you could write the issue down in 1-2 sentence or just upload a picture of it.
http://i.imgur.com/c59tpkj.png

**Comment by SnakeTheRipper** [comment] 2015-01-06 21:24
Well, Jing offers making a photo or a video. I thought it would be cooler to show it on a video. When you record the video, Jing autocreates the shockwave flash and uploads it.

**Comment by dretax** [comment] 2015-01-06 21:30
Whats the problem with swf? I dont get It......-.-
